import"./assets/modulepreload-polyfill-3cfb730f.js";import{a as g,i as d,b as S}from"./assets/vendor-64d08f96.js";class ${constructor(){this.BASE_URL="https://books-backend.p.goit.global/books",this.CATEGORY_LIST="/category-list",this.TOP_BOOKS="/top-books",this.CATEGORY="/category?category="}async getCategories(){const t=this.BASE_URL+this.CATEGORY_LIST;try{return(await g.get(t)).data}catch(e){console.log(e),iziToast.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${e.message}`,position:"topRight"})}}async getTopBooks(){const t=this.BASE_URL+this.TOP_BOOKS;try{return(await g.get(t)).data}catch(e){console.log(e),iziToast.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${e.message}`,position:"topRight"})}}async getCategory(t){const e=this.BASE_URL+this.CATEGORY+t;try{return(await g.get(e)).data}catch(s){console.log(s),iziToast.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${s.message}`,position:"topRight"})}}async getBook(t){const e=this.BASE_URL+"/"+t;try{return(await g.get(e)).data}catch(s){console.log(s),iziToast.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${s.message}`,position:"topRight"})}}}const u=new $,y=document.querySelector(".categories-list"),l=document.querySelector(".category");document.querySelector(".shopping-list");const n=JSON.parse(localStorage.getItem("books"))||[];async function _(){try{const t=(await u.getCategories()).map(({list_name:e})=>`<a class="category-link" href=""><li>${e}</li></a>`).join("");y.insertAdjacentHTML("beforeend",t)}catch(o){console.log(o),d.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${o.message}`,position:"topRight"})}}async function E(){try{(await u.getTopBooks()).forEach(t=>{const e=`<h2>${t.list_name}</h2>`,s=`<button class="category-btn" data-category="${t.list_name}" type="button">See more</button>`,i=t.books.map(a=>`
        <div class="book" id="${a._id}">
          <img src="${a.book_image}" alt="${a.title}">
          <h3>${a.title}</h3>
          <p class="description">${a.description}</p>
          <p class="author">Author: ${a.author}</p>
          <p class="publisher"=>Publisher: ${a.publisher}</p>
          <a class="amazon-link" href="${a.amazon_product_url}" target="_blank">Buy on Amazon</a>
        </div>`).join(""),r=e+s+i;l.insertAdjacentHTML("beforeend",r)})}catch(o){console.log(o),d.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${o.message}`,position:"topRight"})}}async function f(o){try{const t=await u.getCategory(o),e=`<h2>${o}</h2>`,s=t.map(r=>`
      <div class="book" id="${r._id}">
        <img src="${r.book_image}" alt="${r.title}">
        <h3>${r.title}</h3>
        <p class="description">${r.description}</p>
        <p class="author">Author: ${r.author}</p>
        <p class="publisher">Publisher: ${r.publisher}</p>
        <a class="amazon-link" href="${r.amazon_product_url}" target="_blank">Buy on Amazon</a>
      </div>`).join(""),i=e+s;l.insertAdjacentHTML("beforeend",i)}catch(t){console.log(t),d.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${t.message}`,position:"topRight"})}}function w(o){o.preventDefault(),l.innerHTML="";const t=o.target.textContent;f(t)}function T(o){if(!o.target.classList.contains("category-btn"))return;const t=o.target.dataset.category;l.innerHTML="",f(t)}async function L(o){const t=o.target.closest(".book");if(!t)return;const e=t.id,s=t.querySelector("h3").textContent,i=t.querySelector(".description").textContent,r=t.querySelector(".author").textContent,a=t.querySelector(".publisher").textContent,c=t.querySelector("img").src,h=t.querySelector(".amazon-link").href,m=t.querySelector(".modal-text"),b={_id:e,title:s,description:i,author:r,publisher:a,book_image:c,amazon_product_url:h};if(o.target.textContent==="Add to shopping list"){if(m.style.display="block",n.find(p=>p._id===e))return;o.target.textContent="Remove from shopping list",n.push(b),localStorage.setItem("books",JSON.stringify(n))}else if(o.target.textContent==="Remove from shopping list"){m.style.display="none";const p=n.findIndex(k=>k._id===e);p!==-1&&(n.splice(p,1),localStorage.setItem("books",JSON.stringify(n)),o.target.textContent="Add to shopping list")}}async function A(o){if(o.preventDefault(),o.target.nodeName!=="IMG")return;o.stopPropagation();const t=o.target.parentNode.id;try{const e=await u.getBook(t);let s="Add to shopping list";n.findIndex(c=>c._id===e._id)>-1&&(s="Remove from shopping list");const i=`
  <li class="book" id="${e._id}">
    <img src="${e.book_image}" alt="${e.title}">
    <h3>${e.title}</h3>
    <p class="description">${e.description}</p>
    <p class="author">Author: ${e.author}</p>
    <p class="publisher">Publisher: ${e.publisher}</p>
    <a class="amazon-link" href="${e.amazon_product_url}" target="_blank">Buy on Amazon</a>
    <button class="add-btn" type="button">${s}</button>
    <p class="modal-text">Сongratulations! You have added the book to the shopping list. To delete, press the button “Remove from the shopping list”.</p>
  </li>`,r=c=>{c.code==="Escape"&&a.close()},a=S.create(i,{className:"modal",onShow:()=>{const c=a.element().querySelector(".modal-text");n.find(h=>h._id===t)&&c.classList.add("visible"),document.addEventListener("keydown",r),document.addEventListener("click",L)},onClose:()=>{document.removeEventListener("keydown",r)}});a.show()}catch(e){console.log(e),d.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${e.message}`,position:"topRight"})}}y.addEventListener("click",w);l.addEventListener("click",T);l.addEventListener("click",A);_();E();
//# sourceMappingURL=commonHelpers.js.map
