import"./assets/modulepreload-polyfill-3cfb730f.js";import{a as d,i as u,b as S}from"./assets/vendor-64d08f96.js";class ${constructor(){this.BASE_URL="https://books-backend.p.goit.global/books",this.CATEGORY_LIST="/category-list",this.TOP_BOOKS="/top-books",this.CATEGORY="/category?category="}async getCategories(){const e=this.BASE_URL+this.CATEGORY_LIST;try{return(await d.get(e)).data}catch(t){console.log(t),iziToast.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${t.message}`,position:"topRight"})}}async getTopBooks(){const e=this.BASE_URL+this.TOP_BOOKS;try{return(await d.get(e)).data}catch(t){console.log(t),iziToast.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${t.message}`,position:"topRight"})}}async getCategory(e){const t=this.BASE_URL+this.CATEGORY+e;try{return(await d.get(t)).data}catch(s){console.log(s),iziToast.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${s.message}`,position:"topRight"})}}async getBook(e){const t=this.BASE_URL+"/"+e;try{return(await d.get(t)).data}catch(s){console.log(s),iziToast.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${s.message}`,position:"topRight"})}}}const h=new $,y=document.querySelector(".categories-list"),p=document.querySelector(".category");document.querySelector(".shopping-list");const l=JSON.parse(localStorage.getItem("books"))||[];async function E(){try{const e=(await h.getCategories()).map(({list_name:s})=>`<a class="category-link" href=""><li>${s}</li></a>`).join("");y.insertAdjacentHTML("beforeend",e),document.querySelectorAll(".category-link").forEach(s=>{s.addEventListener("click",c=>{const n=document.querySelector(".category-link .active");n&&n.classList.remove("active"),c.target.classList.add("active")})})}catch(o){console.log(o),u.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${o.message}`,position:"topRight"})}}async function _(){try{(await h.getTopBooks()).forEach(e=>{const t=`<h2>${e.list_name}</h2>`,s=`<button class="category-btn" data-category="${e.list_name}" type="button">See more</button>`,c=e.books.map(r=>`
        <div class="book" id="${r._id}">
          <img src="${r.book_image}" alt="${r.title}">
          <h3>${r.title}</h3>
          <p class="description">${r.description}</p>
          <p class="author">Author: ${r.author}</p>
          <p class="publisher"=>Publisher: ${r.publisher}</p>
          <a class="amazon-link" href="${r.amazon_product_url}" target="_blank">Buy on Amazon</a>
        </div>`).join(""),n=t+s+c;p.insertAdjacentHTML("beforeend",n)})}catch(o){console.log(o),u.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${o.message}`,position:"topRight"})}}async function f(o){try{const e=await h.getCategory(o),t=o.split(" "),s=t[t.length-1],n=`<h2 class="category-header">${t.slice(0,t.length-1).join(" ")} <span class="last-word-color">${s}</span></h2>`,r=e.map(a=>`
      <div class="book" id="${a._id}">
        <img src="${a.book_image}" alt="${a.title}">
        <h3>${a.title}</h3>
        <p class="description">${a.description}</p>
        <p class="author">Author: ${a.author}</p>
        <p class="publisher">Publisher: ${a.publisher}</p>
        <a class="amazon-link" href="${a.amazon_product_url}" target="_blank">Buy on Amazon</a>
      </div>`).join(""),i=n+r;p.insertAdjacentHTML("beforeend",i)}catch(e){console.log(e),u.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${e.message}`,position:"topRight"})}}function L(o){o.preventDefault(),p.innerHTML="";const e=o.target.textContent;f(e)}function w(o){if(!o.target.classList.contains("category-btn"))return;const e=o.target.dataset.category;p.innerHTML="",f(e)}async function T(o){const e=o.target.closest(".book");if(!e)return;const t=e.id,s=e.querySelector("h3").textContent,c=e.querySelector(".description").textContent,n=e.querySelector(".author").textContent,r=e.querySelector(".publisher").textContent,i=e.querySelector("img").src,a=e.querySelector(".amazon-link").href,m=e.querySelector(".modal-text"),k={_id:t,title:s,description:c,author:n,publisher:r,book_image:i,amazon_product_url:a};if(o.target.textContent==="Add to shopping list"){if(m.style.display="block",l.find(g=>g._id===t))return;o.target.textContent="Remove from shopping list",l.push(k),localStorage.setItem("books",JSON.stringify(l))}else if(o.target.textContent==="Remove from shopping list"){m.style.display="none";const g=l.findIndex(b=>b._id===t);g!==-1&&(l.splice(g,1),localStorage.setItem("books",JSON.stringify(l)),o.target.textContent="Add to shopping list")}}async function v(o){if(o.preventDefault(),o.target.nodeName!=="IMG")return;o.stopPropagation();const e=o.target.parentNode.id;try{const t=await h.getBook(e);let s="Add to shopping list";l.findIndex(i=>i._id===t._id)>-1&&(s="Remove from shopping list");const c=`
  <div class="book" id="${t._id}">
    <img src="${t.book_image}" alt="${t.title}">
    <h3>${t.title}</h3>
    <p class="description">${t.description}</p>
    <p class="author">Author: ${t.author}</p>
    <p class="publisher">Publisher: ${t.publisher}</p>
    <a class="amazon-link" href="${t.amazon_product_url}" target="_blank">Buy on Amazon</a>
    <button class="add-btn" type="button">${s}</button>
    <p class="modal-text">Сongratulations! You have added the book to the shopping list. To delete, press the button “Remove from the shopping list”.</p>
  </div>`,n=i=>{i.code==="Escape"&&r.close()},r=S.create(c,{className:"modal",onShow:()=>{const i=r.element().querySelector(".modal-text");l.find(a=>a._id===e)&&i.classList.add("visible"),document.addEventListener("keydown",n),document.addEventListener("click",T)},onClose:()=>{document.removeEventListener("keydown",n)}});r.show()}catch(t){console.log(t),u.error({title:"Error",message:`Oops! Something went wrong. Please try again later or contact support if the issue persists. Error details: ${t.message}`,position:"topRight"})}}y.addEventListener("click",L);p.addEventListener("click",w);p.addEventListener("click",v);E();_();
//# sourceMappingURL=commonHelpers.js.map
